-- AUTOGENERATED stub loader — DO NOT EDIT BY HAND.
-- Ensures doFile('./scripts/h55_enums_spells.lua') works in both H5M and H5U layouts.
__h55__local_56424_PCALL = _h55_pcall
if not __h55__local_56424_PCALL then __h55__local_56424_PCALL = pcall end
__h55__local_56424_OK = nil
if __h55__local_56424_PCALL(function() doFile('./h55_enums_spells.lua') end) then
  __h55__local_56424_OK = 1
elseif __h55__local_56424_PCALL(function() doFile('h55_enums_spells.lua') end) then
  __h55__local_56424_OK = 1
end
if not __h55__local_56424_OK then
  if write then write('[H55 ENUMS] ERR: cannot load h55_enums_spells.lua via scripts/ loader.\n') end
  if ShowFlyingSign and GetCurrentPlayer and GetPlayerMainHero then
    __h55__local_56424_msg = 'H55 ENUMS: load error h55_enums_spells.lua'
    __h55__local_56424_hero = GetPlayerMainHero(GetCurrentPlayer())
    if __h55__local_56424_hero then
      if startThread then startThread(ShowFlyingSign, __h55__local_56424_msg, __h55__local_56424_hero, 4)
      else ShowFlyingSign(__h55__local_56424_msg, __h55__local_56424_hero, 4) end
    end
    __h55__local_56424_msg = nil
    __h55__local_56424_hero = nil
  end
end
__h55__local_56424_PCALL = nil
__h55__local_56424_OK = nil
