-- ============================================================================
-- H55 ENUMS · SPELLS (READ‑ONLY, LUA 4.0–SAFE)
-- ----------------------------------------------------------------------------
-- Purpose
--   Provides a stable, read‑only, flat enumeration API for spell tokens used
--   by Heroes V scripts. Data are frozen at load time.
--
-- Loading & Safety
--   - This file requires './scripts/h55_enum_runtime.lua' which defines
--     freeze_shallow() used here to enforce immutability of the top‑level map.
--   - All exported tables MUST be treated as read‑only. Writes are blocked
--     by the runtime and must raise an error.
--   - It is safe to load/include this file multiple times.
--   - For H5M/H5U compatibility, you can load via a stub:
--         doFile('./scripts/h55_enums_spells.lua')
--     which falls back to './h55_enums_spells.lua' when needed.
--
-- Public API (read‑only)
--   SPELL : table<string, Spell>   -- Flat map keyed by SPELL symbol
--                                   -- (e.g., 'ARMAGEDDON', 'DISPEL').
--     Spell (record):
--       name  : string  -- Generator symbol for the spell
--                        -- (e.g., 'SPELL_ARMAGEDDON').
--       const : string  -- Engine token to interoperate with game code
--                        -- (e.g., 'SPELL_ARMAGEDDON'). Use this when an
--                        -- engine API requires a SPELL_* constant.
--
-- Contract & Invariants
--   - Keys are ASCII, UPPERCASE, underscore‑separated, and case‑sensitive.
--   - The map is flat (no faction or school sub‑namespaces in this file).
--   - Names/tokens that are non‑canonical in spelling (if any) are preserved
--     exactly to match engine tokens.
--   - Missing lookups return nil; no guards are added by this file.
--
-- Regeneration & Compatibility
--   - This file is auto‑generated. Keys (spell symbols) form the stable API
--     surface; new entries may be added in future exports.
--   - Designed for Lua 4.0. Data are plain tables and strings and remain
--     forward‑compatible with Lua versions that preserve base table semantics.
--
-- References (specifications)
--   - Lua 4.0 Reference Manual — Ierusalimschy, de Figueiredo, Celes.
--     (authoritative semantics for tables, strings, and metatables).
--   - Heroes V engine enumeration tokens (SPELL_*) as defined by the
--     game engine / SDK.
-- ============================================================================
-- AUTOGENERATED by h5_exporter.py — DO NOT EDIT BY HAND.
-- Heroes V / Lua 4.0–safe runtime include with path fallbacks (no busy-wait).
if not __h55__local_56424_freeze then
  __h55__local_56424_PCALL = _h55_pcall
  if not __h55__local_56424_PCALL then __h55__local_56424_PCALL = pcall end

  if __h55__local_56424_PCALL(function() doFile('./scripts/h55_enum_runtime.lua') end) then
  elseif __h55__local_56424_PCALL(function() doFile('./h55_enum_runtime.lua') end) then
  elseif __h55__local_56424_PCALL(function() doFile('scripts/h55_enum_runtime.lua') end) then
  else
    __h55__local_56424_PCALL(function() doFile('h55_enum_runtime.lua') end)
  end

  if not __h55__local_56424_freeze then
    if write then write('[H55 ENUMS] WARN: missing runtime (h55_enum_runtime.lua). Enums will not be read-only.\n') end
    if ShowFlyingSign and GetCurrentPlayer and GetPlayerMainHero then
      __h55__local_56424_msg = 'H55 ENUMS: runtime missing; enums not read-only'
      __h55__local_56424_hero = GetPlayerMainHero(GetCurrentPlayer())
      if __h55__local_56424_hero then
        if startThread then startThread(ShowFlyingSign, __h55__local_56424_msg, __h55__local_56424_hero, 4)
        else ShowFlyingSign(__h55__local_56424_msg, __h55__local_56424_hero, 4) end
      end
      __h55__local_56424_msg = nil
      __h55__local_56424_hero = nil
    end
    -- Degrade gracefully: identity freeze helpers so the file keeps working.
    function __h55__local_56424_freeze(tbl) return tbl end
    function __h55__local_56424_freeze_shallow(tbl)
      if type(tbl) == "table" then
        foreach(tbl, function(k, v)
          if type(v) == "table" then __h55__local_56424_freeze(v) end
        end)
      end
      return tbl
    end
  end
  __h55__local_56424_PCALL = nil
end

-- Spells enumeration (flat), read-only (best effort in Lua 4.0)
SPELL = __h55__local_56424_freeze_shallow({
  ANIMATE_DEAD = { name = 'SPELL_ANIMATE_DEAD', const = 'SPELL_ANIMATE_DEAD' },
  ANTIMAGIC = { name = 'SPELL_ANTIMAGIC', const = 'SPELL_ANTIMAGIC' },
  ARCANECRYSTAL = { name = 'SPELL_ARCANECRYSTAL', const = 'SPELL_ARCANECRYSTAL' },
  ARMAGEDDON = { name = 'SPELL_ARMAGEDDON', const = 'SPELL_ARMAGEDDON' },
  BERSERK = { name = 'SPELL_BERSERK', const = 'SPELL_BERSERK' },
  BLADEBARRIER = { name = 'SPELL_BLADEBARRIER', const = 'SPELL_BLADEBARRIER' },
  BLESS = { name = 'SPELL_BLESS', const = 'SPELL_BLESS' },
  BLIND = { name = 'SPELL_BLIND', const = 'SPELL_BLIND' },
  BLOODLUST = { name = 'SPELL_BLOODLUST', const = 'SPELL_BLOODLUST' },
  CELESTIAL_SHIELD = { name = 'SPELL_CELESTIAL_SHIELD', const = 'SPELL_CELESTIAL_SHIELD' },
  CHAIN_LIGHTNING_HIT = { name = 'SPELL_CHAIN_LIGHTNING_HIT', const = 'SPELL_CHAIN_LIGHTNING_HIT' },
  CONJUREPHOENIX = { name = 'SPELL_CONJUREPHOENIX', const = 'SPELL_CONJUREPHOENIX' },
  CURSE = { name = 'SPELL_CURSE', const = 'SPELL_CURSE' },
  DEEPFREEZE = { name = 'SPELL_DEEPFREEZE', const = 'SPELL_DEEPFREEZE' },
  DEFLECT_ARROWS = { name = 'SPELL_DEFLECT_ARROWS', const = 'SPELL_DEFLECT_ARROWS' },
  DISPEL = { name = 'SPELL_DISPEL', const = 'SPELL_DISPEL' },
  DISRUPTING_RAY = { name = 'SPELL_DISRUPTING_RAY', const = 'SPELL_DISRUPTING_RAY' },
  DIVINEVENGEANCE = { name = 'SPELL_DIVINEVENGEANCE', const = 'SPELL_DIVINEVENGEANCE' },
  EARTHQUAKE = { name = 'SPELL_EARTHQUAKE', const = 'SPELL_EARTHQUAKE' },
  EMPOWERED_ARMAGEDDON = { name = 'SPELL_EMPOWERED_ARMAGEDDON', const = 'SPELL_EMPOWERED_ARMAGEDDON' },
  EMPOWERED_CHAIN_LIGHTNING = { name = 'SPELL_EMPOWERED_CHAIN_LIGHTNING', const = 'SPELL_EMPOWERED_CHAIN_LIGHTNING' },
  EMPOWERED_DEEPFREEZE = { name = 'SPELL_EMPOWERED_DEEPFREEZE', const = 'SPELL_EMPOWERED_DEEPFREEZE' },
  EMPOWERED_FIREBALL = { name = 'SPELL_EMPOWERED_FIREBALL', const = 'SPELL_EMPOWERED_FIREBALL' },
  EMPOWERED_FROST_RING = { name = 'SPELL_EMPOWERED_FROST_RING', const = 'SPELL_EMPOWERED_FROST_RING' },
  EMPOWERED_ICE_BOLT = { name = 'SPELL_EMPOWERED_ICE_BOLT', const = 'SPELL_EMPOWERED_ICE_BOLT' },
  EMPOWERED_IMPLOSION = { name = 'SPELL_EMPOWERED_IMPLOSION', const = 'SPELL_EMPOWERED_IMPLOSION' },
  EMPOWERED_LIGHTNING_BOLT = { name = 'SPELL_EMPOWERED_LIGHTNING_BOLT', const = 'SPELL_EMPOWERED_LIGHTNING_BOLT' },
  EMPOWERED_MAGICFIST = { name = 'SPELL_EMPOWERED_MAGICFIST', const = 'SPELL_EMPOWERED_MAGICFIST' },
  EMPOWERED_MAGIC_ARROW = { name = 'SPELL_EMPOWERED_MAGIC_ARROW', const = 'SPELL_EMPOWERED_MAGIC_ARROW' },
  EMPOWERED_METEOR_SHOWER = { name = 'SPELL_EMPOWERED_METEOR_SHOWER', const = 'SPELL_EMPOWERED_METEOR_SHOWER' },
  EMPOWERED_STONESPIKES = { name = 'SPELL_EMPOWERED_STONESPIKES', const = 'SPELL_EMPOWERED_STONESPIKES' },
  FIREBALL = { name = 'SPELL_FIREBALL', const = 'SPELL_FIREBALL' },
  FIREWALL = { name = 'SPELL_FIREWALL', const = 'SPELL_FIREWALL' },
  FORGETFULNESS = { name = 'SPELL_FORGETFULNESS', const = 'SPELL_FORGETFULNESS' },
  FROST_RING = { name = 'SPELL_FROST_RING', const = 'SPELL_FROST_RING' },
  HASTE = { name = 'SPELL_HASTE', const = 'SPELL_HASTE' },
  HOLY_WORD = { name = 'SPELL_HOLY_WORD', const = 'SPELL_HOLY_WORD' },
  HYPNOTIZE = { name = 'SPELL_HYPNOTIZE', const = 'SPELL_HYPNOTIZE' },
  ICE_BOLT = { name = 'SPELL_ICE_BOLT', const = 'SPELL_ICE_BOLT' },
  IMPLOSION = { name = 'SPELL_IMPLOSION', const = 'SPELL_IMPLOSION' },
  LAND_MINE = { name = 'SPELL_LAND_MINE', const = 'SPELL_LAND_MINE' },
  LIGHTNING_BOLT = { name = 'SPELL_LIGHTNING_BOLT', const = 'SPELL_LIGHTNING_BOLT' },
  MAGICFIST = { name = 'SPELL_MAGICFIST', const = 'SPELL_MAGICFIST' },
  MAGIC_ARROW = { name = 'SPELL_MAGIC_ARROW', const = 'SPELL_MAGIC_ARROW' },
  MASS_BLESS = { name = 'SPELL_MASS_BLESS', const = 'SPELL_MASS_BLESS' },
  MASS_BLOODLAST = { name = 'SPELL_MASS_BLOODLAST', const = 'SPELL_MASS_BLOODLAST' },
  MASS_CURSE = { name = 'SPELL_MASS_CURSE', const = 'SPELL_MASS_CURSE' },
  MASS_DEFLECT_ARROWS = { name = 'SPELL_MASS_DEFLECT_ARROWS', const = 'SPELL_MASS_DEFLECT_ARROWS' },
  MASS_DISPEL = { name = 'SPELL_MASS_DISPEL', const = 'SPELL_MASS_DISPEL' },
  MASS_DISRUPTING_RAY = { name = 'SPELL_MASS_DISRUPTING_RAY', const = 'SPELL_MASS_DISRUPTING_RAY' },
  MASS_FORGETFULNESS = { name = 'SPELL_MASS_FORGETFULNESS', const = 'SPELL_MASS_FORGETFULNESS' },
  MASS_HASTE = { name = 'SPELL_MASS_HASTE', const = 'SPELL_MASS_HASTE' },
  MASS_PLAGUE = { name = 'SPELL_MASS_PLAGUE', const = 'SPELL_MASS_PLAGUE' },
  MASS_SLOW = { name = 'SPELL_MASS_SLOW', const = 'SPELL_MASS_SLOW' },
  MASS_STONESKIN = { name = 'SPELL_MASS_STONESKIN', const = 'SPELL_MASS_STONESKIN' },
  MASS_WEAKNESS = { name = 'SPELL_MASS_WEAKNESS', const = 'SPELL_MASS_WEAKNESS' },
  METEOR_SHOWER = { name = 'SPELL_METEOR_SHOWER', const = 'SPELL_METEOR_SHOWER' },
  PHANTOM = { name = 'SPELL_PHANTOM', const = 'SPELL_PHANTOM' },
  PLAGUE = { name = 'SPELL_PLAGUE', const = 'SPELL_PLAGUE' },
  REGENERATION = { name = 'SPELL_REGENERATION', const = 'SPELL_REGENERATION' },
  RESURRECT = { name = 'SPELL_RESURRECT', const = 'SPELL_RESURRECT' },
  RUNEOFBATTLERAGE_SPELL = { name = 'SPELL_RUNEOFBATTLERAGE_SPELL', const = 'SPELL_RUNEOFBATTLERAGE_SPELL' },
  RUNEOFBERSERKING_SPELL = { name = 'SPELL_RUNEOFBERSERKING_SPELL', const = 'SPELL_RUNEOFBERSERKING_SPELL' },
  RUNEOFCHARGE_SPELL = { name = 'SPELL_RUNEOFCHARGE_SPELL', const = 'SPELL_RUNEOFCHARGE_SPELL' },
  RUNEOFDRAGONFORM_SPELL = { name = 'SPELL_RUNEOFDRAGONFORM_SPELL', const = 'SPELL_RUNEOFDRAGONFORM_SPELL' },
  RUNEOFELEMENTALIMMUNITY_SPELL = { name = 'SPELL_RUNEOFELEMENTALIMMUNITY_SPELL', const = 'SPELL_RUNEOFELEMENTALIMMUNITY_SPELL' },
  RUNEOFETHREALNESS_SPELL = { name = 'SPELL_RUNEOFETHREALNESS_SPELL', const = 'SPELL_RUNEOFETHREALNESS_SPELL' },
  RUNEOFEXORCISM_SPELL = { name = 'SPELL_RUNEOFEXORCISM_SPELL', const = 'SPELL_RUNEOFEXORCISM_SPELL' },
  RUNEOFMAGICCONTROL_SPELL = { name = 'SPELL_RUNEOFMAGICCONTROL_SPELL', const = 'SPELL_RUNEOFMAGICCONTROL_SPELL' },
  RUNEOFREVIVE_SPELL = { name = 'SPELL_RUNEOFREVIVE_SPELL', const = 'SPELL_RUNEOFREVIVE_SPELL' },
  RUNEOFSTUNNING_SPELL = { name = 'SPELL_RUNEOFSTUNNING_SPELL', const = 'SPELL_RUNEOFSTUNNING_SPELL' },
  SLOW = { name = 'SPELL_SLOW', const = 'SPELL_SLOW' },
  SORROW = { name = 'SPELL_SORROW', const = 'SPELL_SORROW' },
  STONESKIN = { name = 'SPELL_STONESKIN', const = 'SPELL_STONESKIN' },
  STONESPIKES = { name = 'SPELL_STONESPIKES', const = 'SPELL_STONESPIKES' },
  SUMMONHIVE = { name = 'SPELL_SUMMONHIVE', const = 'SPELL_SUMMONHIVE' },
  SUMMON_ELEMENTALS = { name = 'SPELL_SUMMON_ELEMENTALS', const = 'SPELL_SUMMON_ELEMENTALS' },
  TELEPORT = { name = 'SPELL_TELEPORT', const = 'SPELL_TELEPORT' },
  UNHOLY_WORD = { name = 'SPELL_UNHOLY_WORD', const = 'SPELL_UNHOLY_WORD' },
  VAMPIRISM = { name = 'SPELL_VAMPIRISM', const = 'SPELL_VAMPIRISM' },
  WASP_SWARM = { name = 'SPELL_WASP_SWARM', const = 'SPELL_WASP_SWARM' },
  WEAKNESS = { name = 'SPELL_WEAKNESS', const = 'SPELL_WEAKNESS' },
})
