-- ============================================================================
-- H55 ENUMS · CREATURES & ABILITIES (READ‑ONLY, LUA 4.0–SAFE)
-- ----------------------------------------------------------------------------
-- Purpose
--   Provides a stable, read‑only enumeration API for creature metadata and
--   creature abilities for Heroes V scripts. Data are frozen at load time.
--
-- Loading & Safety
--   - This file requires './scripts/h55_enum_runtime.lua' which defines
--     freeze() and freeze_shallow() used here to enforce immutability.
--   - All exported tables MUST be treated as read‑only. Writes are blocked
--     by metatables installed by the runtime and must raise an error.
--   - It is safe to load/include this file multiple times.
--   - For H5M/H5U compatibility, you can load via a stub:
--         doFile('./scripts/h55_enums_creatures.lua')
--     which falls back to './h55_enums_creatures.lua' when needed.
--
-- Public API (read‑only)
--   ABILITIES (table)                        -- Namespace root for abilities.
--     .CREATURES : table<string, Ability>    -- Flat map keyed by ABILITY symbol
--                                             -- (e.g., 'ACID_BLOOD').
--       Ability (record):
--         id    : integer  -- Reserved numeric id. May be 0 if not defined by
--                           -- the engine. Do NOT rely on 0/ non‑0 semantics.
--         name  : string   -- Generator symbol for the ability
--                           -- (e.g., 'ACID_BLOOD' as seen in this file).
--         const : string   -- Engine token to interoperate with game code
--                           -- (e.g., 'ABILITY_ACID_BLOOD'). Use this when an
--                           -- engine API requires an ABILITY_* constant.
--
--   CREATURE (table)                         -- Namespace root for creatures.
--     .<FACTION> (table)                     -- Faction namespaces:
--       ACADEMY, DUNGEON, DWARF, FORTRESS, HAVEN, INFERNO,
--       NECROPOLIS, NEUTRALS, ORCS, PRESERVE, UNKNOWN.
--     .<FACTION>.<UNIT> : Creature           -- Leaf records (one per unit).
--       Creature (record):
--         name        : string   -- Generator symbol for the creature
--                                 -- (e.g., 'CREATURE_ARCH_MAGI').
--         id          : integer  -- Reserved numeric id. May be 0.
--         BASE_GROWTH : integer  -- Weekly base growth in town dwellings.
--         ABILITIES   : string[] -- Array of ability KEYS, each of which MUST
--                                 -- exist in ABILITIES.CREATURES. Elements are
--                                 -- ability symbols like 'NO_RANGE_PENALTY'.
--
-- Contract & Invariants
--   - Keys are ASCII, UPPERCASE, underscore‑separated, and case‑sensitive.
--   - ABILITIES arrays contain ability KEYS (strings), not the Ability records.
--     To interoperate with the engine, map a key K as:
--       ABILITIES.CREATURES[K].const  -- engine token 'ABILITY_*'
--   - Missing lookups return nil; no guards are added by this file.
--   - Names/tokens that are non‑canonical in spelling (if any) are preserved
--     exactly to match engine tokens.
--
-- Regeneration & Compatibility
--   - This file is auto‑generated. Keys (ability and creature symbols) form the
--     stable API surface; new entries may be added in future exports.
--   - Designed for Lua 4.0. Data are plain tables and strings and remain
--     forward‑compatible with Lua versions that preserve base table semantics.
--
-- Optional Self‑Test
--   - If the global H55_ENUMS_SELFTEST is set to a truthy value BEFORE loading,
--     the file prints a few sample records via 'write'. No state is mutated.
--
-- References (specifications)
--   - Lua 4.0 Reference Manual — Ierusalimschy, de Figueiredo, Celes.
--     (authoritative semantics for tables, strings, and metatables).
--   - Heroes V engine enumeration tokens (ABILITY_*, CREATURE_*) as defined by
--     the game engine / SDK.
-- ============================================================================
-- AUTOGENERATED by h5_exporter.py — DO NOT EDIT BY HAND.
-- Heroes V / Lua 4.0–safe runtime include with path fallbacks (no busy-wait).
if not __h55__local_56424_freeze then
  __h55__local_56424_PCALL = _h55_pcall
  if not __h55__local_56424_PCALL then __h55__local_56424_PCALL = pcall end

  if __h55__local_56424_PCALL(function() doFile('./scripts/h55_enum_runtime.lua') end) then
  elseif __h55__local_56424_PCALL(function() doFile('./h55_enum_runtime.lua') end) then
  elseif __h55__local_56424_PCALL(function() doFile('scripts/h55_enum_runtime.lua') end) then
  else
    __h55__local_56424_PCALL(function() doFile('h55_enum_runtime.lua') end)
  end

  if not __h55__local_56424_freeze then
    if write then write('[H55 ENUMS] WARN: missing runtime (h55_enum_runtime.lua). Enums will not be read-only.\n') end
    if ShowFlyingSign and GetCurrentPlayer and GetPlayerMainHero then
      __h55__local_56424_msg = 'H55 ENUMS: runtime missing; enums not read-only'
      __h55__local_56424_hero = GetPlayerMainHero(GetCurrentPlayer())
      if __h55__local_56424_hero then
        if startThread then startThread(ShowFlyingSign, __h55__local_56424_msg, __h55__local_56424_hero, 4)
        else ShowFlyingSign(__h55__local_56424_msg, __h55__local_56424_hero, 4) end
      end
      __h55__local_56424_msg = nil
      __h55__local_56424_hero = nil
    end
    -- Degrade gracefully: identity freeze helpers so the file keeps working.
    function __h55__local_56424_freeze(tbl) return tbl end
    function __h55__local_56424_freeze_shallow(tbl)
      if type(tbl) == "table" then
        foreach(tbl, function(k, v)
          if type(v) == "table" then __h55__local_56424_freeze(v) end
        end)
      end
      return tbl
    end
  end
  __h55__local_56424_PCALL = nil
end

ABILITIES = ABILITIES or {}
ABILITIES.CREATURES = __h55__local_56424_freeze_shallow({
  ACID_BLOOD = { id = 0, name = 'ACID_BLOOD', const = 'ABILITY_ACID_BLOOD' },
  ACID_BREATH = { id = 0, name = 'ACID_BREATH', const = 'ABILITY_ACID_BREATH' },
  AGILITY = { id = 0, name = 'AGILITY', const = 'ABILITY_AGILITY' },
  AMMO_STEAL = { id = 0, name = 'AMMO_STEAL', const = 'ABILITY_AMMO_STEAL' },
  ANTI_GIANT = { id = 0, name = 'ANTI_GIANT', const = 'ABILITY_ANTI_GIANT' },
  ARMORED = { id = 0, name = 'ARMORED', const = 'ABILITY_ARMORED' },
  AURA_OF_BRAVERY = { id = 0, name = 'AURA_OF_BRAVERY', const = 'ABILITY_AURA_OF_BRAVERY' },
  AURA_OF_FIRE_VULNERABILITY = { id = 0, name = 'AURA_OF_FIRE_VULNERABILITY', const = 'ABILITY_AURA_OF_FIRE_VULNERABILITY' },
  AURA_OF_ICE_VULNERABILITY = { id = 0, name = 'AURA_OF_ICE_VULNERABILITY', const = 'ABILITY_AURA_OF_ICE_VULNERABILITY' },
  AURA_OF_LIGHTNING_VULNERABILITY = { id = 0, name = 'AURA_OF_LIGHTNING_VULNERABILITY', const = 'ABILITY_AURA_OF_LIGHTNING_VULNERABILITY' },
  AURA_OF_MAGIC_RESISTANCE = { id = 0, name = 'AURA_OF_MAGIC_RESISTANCE', const = 'ABILITY_AURA_OF_MAGIC_RESISTANCE' },
  AXE_OF_SLAUGHTER = { id = 0, name = 'AXE_OF_SLAUGHTER', const = 'ABILITY_AXE_OF_SLAUGHTER' },
  BALOR_SUMMONIG = { id = 0, name = 'BALOR_SUMMONIG', const = 'ABILITY_BALOR_SUMMONIG' },
  BASH = { id = 0, name = 'BASH', const = 'ABILITY_BASH' },
  BATTLE_DIVE = { id = 0, name = 'BATTLE_DIVE', const = 'ABILITY_BATTLE_DIVE' },
  BATTLE_FRENZY = { id = 0, name = 'BATTLE_FRENZY', const = 'ABILITY_BATTLE_FRENZY' },
  BATTLE_RAGE = { id = 0, name = 'BATTLE_RAGE', const = 'ABILITY_BATTLE_RAGE' },
  BEAR_ROAR = { id = 0, name = 'BEAR_ROAR', const = 'ABILITY_BEAR_ROAR' },
  BERSERKER_RAGE = { id = 0, name = 'BERSERKER_RAGE', const = 'ABILITY_BERSERKER_RAGE' },
  BLINDING_ATTACK = { id = 0, name = 'BLINDING_ATTACK', const = 'ABILITY_BLINDING_ATTACK' },
  BOND_OF_LIGHT = { id = 0, name = 'BOND_OF_LIGHT', const = 'ABILITY_BOND_OF_LIGHT' },
  BRAVERY = { id = 0, name = 'BRAVERY', const = 'ABILITY_BRAVERY' },
  BRUTALITY = { id = 0, name = 'BRUTALITY', const = 'ABILITY_BRUTALITY' },
  CALL_LIGHTNING = { id = 0, name = 'CALL_LIGHTNING', const = 'ABILITY_CALL_LIGHTNING' },
  CALL_STORM = { id = 0, name = 'CALL_STORM', const = 'ABILITY_CALL_STORM' },
  CHAIN_SHOT = { id = 0, name = 'CHAIN_SHOT', const = 'ABILITY_CHAIN_SHOT' },
  CLEAVE = { id = 0, name = 'CLEAVE', const = 'ABILITY_CLEAVE' },
  COWARDICE = { id = 0, name = 'COWARDICE', const = 'ABILITY_COWARDICE' },
  CROSS_ATTACK = { id = 0, name = 'CROSS_ATTACK', const = 'ABILITY_CROSS_ATTACK' },
  CRUSHING_BLOW = { id = 0, name = 'CRUSHING_BLOW', const = 'ABILITY_CRUSHING_BLOW' },
  CRYSTAL_SCALES = { id = 0, name = 'CRYSTAL_SCALES', const = 'ABILITY_CRYSTAL_SCALES' },
  CURSING_ATTACK = { id = 0, name = 'CURSING_ATTACK', const = 'ABILITY_CURSING_ATTACK' },
  DASH = { id = 0, name = 'DASH', const = 'ABILITY_DASH' },
  DEATH_CLOUD = { id = 0, name = 'DEATH_CLOUD', const = 'ABILITY_DEATH_CLOUD' },
  DEATH_WAIL = { id = 0, name = 'DEATH_WAIL', const = 'ABILITY_DEATH_WAIL' },
  DEMONIC = { id = 0, name = 'DEMONIC', const = 'ABILITY_DEMONIC' },
  DEMON_RAGED = { id = 0, name = 'DEMON_RAGED', const = 'ABILITY_DEMON_RAGED' },
  DESTRUCTION_MAGIC_MAGNETISM = { id = 0, name = 'DESTRUCTION_MAGIC_MAGNETISM', const = 'ABILITY_DESTRUCTION_MAGIC_MAGNETISM' },
  DOUBLE_ATTACK = { id = 0, name = 'DOUBLE_ATTACK', const = 'ABILITY_DOUBLE_ATTACK' },
  ELDRITCH_AURA = { id = 0, name = 'ELDRITCH_AURA', const = 'ABILITY_ELDRITCH_AURA' },
  ELEMENTAL = { id = 0, name = 'ELEMENTAL', const = 'ABILITY_ELEMENTAL' },
  ELVES_DOUBLE_SHOT = { id = 0, name = 'ELVES_DOUBLE_SHOT', const = 'ABILITY_ELVES_DOUBLE_SHOT' },
  ENCHANTED_OBSIDIAN = { id = 0, name = 'ENCHANTED_OBSIDIAN', const = 'ABILITY_ENCHANTED_OBSIDIAN' },
  ENERGY_CHANNEL = { id = 0, name = 'ENERGY_CHANNEL', const = 'ABILITY_ENERGY_CHANNEL' },
  ENRAGED = { id = 0, name = 'ENRAGED', const = 'ABILITY_ENRAGED' },
  ENTANGLING_ROOTS = { id = 0, name = 'ENTANGLING_ROOTS', const = 'ABILITY_ENTANGLING_ROOTS' },
  EVIL_EYE = { id = 0, name = 'EVIL_EYE', const = 'ABILITY_EVIL_EYE' },
  EXPLOSION = { id = 0, name = 'EXPLOSION', const = 'ABILITY_EXPLOSION' },
  FAST_ATTACK = { id = 0, name = 'FAST_ATTACK', const = 'ABILITY_FAST_ATTACK' },
  FEAR = { id = 0, name = 'FEAR', const = 'ABILITY_FEAR' },
  FIERCE_RETALIATION = { id = 0, name = 'FIERCE_RETALIATION', const = 'ABILITY_FIERCE_RETALIATION' },
  FIRE_BREATH = { id = 0, name = 'FIRE_BREATH', const = 'ABILITY_FIRE_BREATH' },
  FIRE_PROOF_50 = { id = 0, name = 'FIRE_PROOF_50', const = 'ABILITY_FIRE_PROOF_50' },
  FIRE_SHIELD = { id = 0, name = 'FIRE_SHIELD', const = 'ABILITY_FIRE_SHIELD' },
  FLAMESTRIKE = { id = 0, name = 'FLAMESTRIKE', const = 'ABILITY_FLAMESTRIKE' },
  FLAMEWAVE = { id = 0, name = 'FLAMEWAVE', const = 'ABILITY_FLAMEWAVE' },
  FRIGHT_AURA = { id = 0, name = 'FRIGHT_AURA', const = 'ABILITY_FRIGHT_AURA' },
  GOBLIN_THROWER = { id = 0, name = 'GOBLIN_THROWER', const = 'ABILITY_GOBLIN_THROWER' },
  HARM_TOUCH = { id = 0, name = 'HARM_TOUCH', const = 'ABILITY_HARM_TOUCH' },
  HARPOON_STRIKE = { id = 0, name = 'HARPOON_STRIKE', const = 'ABILITY_HARPOON_STRIKE' },
  HEXING_ATTACK = { id = 0, name = 'HEXING_ATTACK', const = 'ABILITY_HEXING_ATTACK' },
  HOLD_GROUND = { id = 0, name = 'HOLD_GROUND', const = 'ABILITY_HOLD_GROUND' },
  HORROR_OF_THE_DEATH = { id = 0, name = 'HORROR_OF_THE_DEATH', const = 'ABILITY_HORROR_OF_THE_DEATH' },
  HOWL = { id = 0, name = 'HOWL', const = 'ABILITY_HOWL' },
  IMMUNITY_TO_AIR = { id = 0, name = 'IMMUNITY_TO_AIR', const = 'ABILITY_IMMUNITY_TO_AIR' },
  IMMUNITY_TO_BERSERK = { id = 0, name = 'IMMUNITY_TO_BERSERK', const = 'ABILITY_IMMUNITY_TO_BERSERK' },
  IMMUNITY_TO_BLIND = { id = 0, name = 'IMMUNITY_TO_BLIND', const = 'ABILITY_IMMUNITY_TO_BLIND' },
  IMMUNITY_TO_CURSE = { id = 0, name = 'IMMUNITY_TO_CURSE', const = 'ABILITY_IMMUNITY_TO_CURSE' },
  IMMUNITY_TO_EARTH = { id = 0, name = 'IMMUNITY_TO_EARTH', const = 'ABILITY_IMMUNITY_TO_EARTH' },
  IMMUNITY_TO_FIRE = { id = 0, name = 'IMMUNITY_TO_FIRE', const = 'ABILITY_IMMUNITY_TO_FIRE' },
  IMMUNITY_TO_HYPNOTIZE = { id = 0, name = 'IMMUNITY_TO_HYPNOTIZE', const = 'ABILITY_IMMUNITY_TO_HYPNOTIZE' },
  IMMUNITY_TO_MAGIC = { id = 0, name = 'IMMUNITY_TO_MAGIC', const = 'ABILITY_IMMUNITY_TO_MAGIC' },
  IMMUNITY_TO_MIND_CONTROL = { id = 0, name = 'IMMUNITY_TO_MIND_CONTROL', const = 'ABILITY_IMMUNITY_TO_MIND_CONTROL' },
  IMMUNITY_TO_SLOW = { id = 0, name = 'IMMUNITY_TO_SLOW', const = 'ABILITY_IMMUNITY_TO_SLOW' },
  IMMUNITY_TO_WATER = { id = 0, name = 'IMMUNITY_TO_WATER', const = 'ABILITY_IMMUNITY_TO_WATER' },
  INCINERATE = { id = 0, name = 'INCINERATE', const = 'ABILITY_INCINERATE' },
  INCORPOREAL = { id = 0, name = 'INCORPOREAL', const = 'ABILITY_INCORPOREAL' },
  INVISIBILITY = { id = 0, name = 'INVISIBILITY', const = 'ABILITY_INVISIBILITY' },
  JOUSTING = { id = 0, name = 'JOUSTING', const = 'ABILITY_JOUSTING' },
  LARGE_SHIELD = { id = 0, name = 'LARGE_SHIELD', const = 'ABILITY_LARGE_SHIELD' },
  LAY_HANDS = { id = 0, name = 'LAY_HANDS', const = 'ABILITY_LAY_HANDS' },
  LEAP = { id = 0, name = 'LEAP', const = 'ABILITY_LEAP' },
  LIFE_DRAIN = { id = 0, name = 'LIFE_DRAIN', const = 'ABILITY_LIFE_DRAIN' },
  LIGHTNING_BREATH = { id = 0, name = 'LIGHTNING_BREATH', const = 'ABILITY_LIGHTNING_BREATH' },
  LIQUID_FLAME_BREATH = { id = 0, name = 'LIQUID_FLAME_BREATH', const = 'ABILITY_LIQUID_FLAME_BREATH' },
  LIZARD_BITE = { id = 0, name = 'LIZARD_BITE', const = 'ABILITY_LIZARD_BITE' },
  LUCK_GAMBLER = { id = 0, name = 'LUCK_GAMBLER', const = 'ABILITY_LUCK_GAMBLER' },
  MAGIC_ATTACK = { id = 0, name = 'MAGIC_ATTACK', const = 'ABILITY_MAGIC_ATTACK' },
  MAGIC_PROOF_25 = { id = 0, name = 'MAGIC_PROOF_25', const = 'ABILITY_MAGIC_PROOF_25' },
  MAGIC_PROOF_50 = { id = 0, name = 'MAGIC_PROOF_50', const = 'ABILITY_MAGIC_PROOF_50' },
  MAGIC_PROOF_75 = { id = 0, name = 'MAGIC_PROOF_75', const = 'ABILITY_MAGIC_PROOF_75' },
  MAGMA_SHIELD = { id = 0, name = 'MAGMA_SHIELD', const = 'ABILITY_MAGMA_SHIELD' },
  MANA_DESTROYER = { id = 0, name = 'MANA_DESTROYER', const = 'ABILITY_MANA_DESTROYER' },
  MANA_DRAIN = { id = 0, name = 'MANA_DRAIN', const = 'ABILITY_MANA_DRAIN' },
  MANA_FEED = { id = 0, name = 'MANA_FEED', const = 'ABILITY_MANA_FEED' },
  MANA_STEALER = { id = 0, name = 'MANA_STEALER', const = 'ABILITY_MANA_STEALER' },
  MANEURE = { id = 0, name = 'MANEURE', const = 'ABILITY_MANEURE' },
  MARK_OF_FIRE = { id = 0, name = 'MARK_OF_FIRE', const = 'ABILITY_MARK_OF_FIRE' },
  MECHANICAL = { id = 0, name = 'MECHANICAL', const = 'ABILITY_MECHANICAL' },
  NO_ENEMY_RETALIATION = { id = 0, name = 'NO_ENEMY_RETALIATION', const = 'ABILITY_NO_ENEMY_RETALIATION' },
  NO_MELEE_PENALTY = { id = 0, name = 'NO_MELEE_PENALTY', const = 'ABILITY_NO_MELEE_PENALTY' },
  NO_RANGE_PENALTY = { id = 0, name = 'NO_RANGE_PENALTY', const = 'ABILITY_NO_RANGE_PENALTY' },
  ORDER_OF_THE_CHIEF = { id = 0, name = 'ORDER_OF_THE_CHIEF', const = 'ABILITY_ORDER_OF_THE_CHIEF' },
  PACK_DIVE = { id = 0, name = 'PACK_DIVE', const = 'ABILITY_PACK_DIVE' },
  PACK_HUNTER = { id = 0, name = 'PACK_HUNTER', const = 'ABILITY_PACK_HUNTER' },
  PAW_STRIKE = { id = 0, name = 'PAW_STRIKE', const = 'ABILITY_PAW_STRIKE' },
  PIERCING_ARROW = { id = 0, name = 'PIERCING_ARROW', const = 'ABILITY_PIERCING_ARROW' },
  POISONOUS_ATTACK = { id = 0, name = 'POISONOUS_ATTACK', const = 'ABILITY_POISONOUS_ATTACK' },
  POWER_FEED = { id = 0, name = 'POWER_FEED', const = 'ABILITY_POWER_FEED' },
  PRECISE_SHOT = { id = 0, name = 'PRECISE_SHOT', const = 'ABILITY_PRECISE_SHOT' },
  PREPARED_POSITION = { id = 0, name = 'PREPARED_POSITION', const = 'ABILITY_PREPARED_POSITION' },
  PRESENCE_OF_COMMANDER = { id = 0, name = 'PRESENCE_OF_COMMANDER', const = 'ABILITY_PRESENCE_OF_COMMANDER' },
  PURGER = { id = 0, name = 'PURGER', const = 'ABILITY_PURGER' },
  RAGE_OF_THE_FOREST = { id = 0, name = 'RAGE_OF_THE_FOREST', const = 'ABILITY_RAGE_OF_THE_FOREST' },
  RANDOM_CASTER = { id = 0, name = 'RANDOM_CASTER', const = 'ABILITY_RANDOM_CASTER' },
  RANDOM_CASTER_BLESS = { id = 0, name = 'RANDOM_CASTER_BLESS', const = 'ABILITY_RANDOM_CASTER_BLESS' },
  RANGED_RETALIATE = { id = 0, name = 'RANGED_RETALIATE', const = 'ABILITY_RANGED_RETALIATE' },
  RANGE_PENALTY = { id = 0, name = 'RANGE_PENALTY', const = 'ABILITY_RANGE_PENALTY' },
  REBIRTH = { id = 0, name = 'REBIRTH', const = 'ABILITY_REBIRTH' },
  REGENERATION = { id = 0, name = 'REGENERATION', const = 'ABILITY_REGENERATION' },
  REPAIR = { id = 0, name = 'REPAIR', const = 'ABILITY_REPAIR' },
  RESURRECT_ALLIES = { id = 0, name = 'RESURRECT_ALLIES', const = 'ABILITY_RESURRECT_ALLIES' },
  RIDER_CHARGE = { id = 0, name = 'RIDER_CHARGE', const = 'ABILITY_RIDER_CHARGE' },
  RIDE_BY_ATTACK = { id = 0, name = 'RIDE_BY_ATTACK', const = 'ABILITY_RIDE_BY_ATTACK' },
  SABOTAGE = { id = 0, name = 'SABOTAGE', const = 'ABILITY_SABOTAGE' },
  SACRIFICE_GOBLIN = { id = 0, name = 'SACRIFICE_GOBLIN', const = 'ABILITY_SACRIFICE_GOBLIN' },
  SCATTER_SHOT = { id = 0, name = 'SCATTER_SHOT', const = 'ABILITY_SCATTER_SHOT' },
  SCAVENGER = { id = 0, name = 'SCAVENGER', const = 'ABILITY_SCAVENGER' },
  SEARING_AURA = { id = 0, name = 'SEARING_AURA', const = 'ABILITY_SEARING_AURA' },
  SEDUCE = { id = 0, name = 'SEDUCE', const = 'ABILITY_SEDUCE' },
  SET_SNARES = { id = 0, name = 'SET_SNARES', const = 'ABILITY_SET_SNARES' },
  SHIELD_OTHER = { id = 0, name = 'SHIELD_OTHER', const = 'ABILITY_SHIELD_OTHER' },
  SHIELD_WALL = { id = 0, name = 'SHIELD_WALL', const = 'ABILITY_SHIELD_WALL' },
  SIX_HEADED_ATTACK = { id = 0, name = 'SIX_HEADED_ATTACK', const = 'ABILITY_SIX_HEADED_ATTACK' },
  SLEEPING_STRIKE = { id = 0, name = 'SLEEPING_STRIKE', const = 'ABILITY_SLEEPING_STRIKE' },
  SORROW_STRIKE = { id = 0, name = 'SORROW_STRIKE', const = 'ABILITY_SORROW_STRIKE' },
  SPRAY_ATTACK = { id = 0, name = 'SPRAY_ATTACK', const = 'ABILITY_SPRAY_ATTACK' },
  STORMBOLT = { id = 0, name = 'STORMBOLT', const = 'ABILITY_STORMBOLT' },
  STORMSTRIKE = { id = 0, name = 'STORMSTRIKE', const = 'ABILITY_STORMSTRIKE' },
  STRIKE_AND_RETURN = { id = 0, name = 'STRIKE_AND_RETURN', const = 'ABILITY_STRIKE_AND_RETURN' },
  SUMMON_OTHER = { id = 0, name = 'SUMMON_OTHER', const = 'ABILITY_SUMMON_OTHER' },
  SWALLOW_GOBLIN = { id = 0, name = 'SWALLOW_GOBLIN', const = 'ABILITY_SWALLOW_GOBLIN' },
  SYPHON_MANA = { id = 0, name = 'SYPHON_MANA', const = 'ABILITY_SYPHON_MANA' },
  TAKE_ROOTS = { id = 0, name = 'TAKE_ROOTS', const = 'ABILITY_TAKE_ROOTS' },
  TAUNT = { id = 0, name = 'TAUNT', const = 'ABILITY_TAUNT' },
  TAXPAYER = { id = 0, name = 'TAXPAYER', const = 'ABILITY_TAXPAYER' },
  THREE_HEADED_ATTACK = { id = 0, name = 'THREE_HEADED_ATTACK', const = 'ABILITY_THREE_HEADED_ATTACK' },
  TREACHERY = { id = 0, name = 'TREACHERY', const = 'ABILITY_TREACHERY' },
  TREEANT_UNION = { id = 0, name = 'TREEANT_UNION', const = 'ABILITY_TREEANT_UNION' },
  UNDEAD = { id = 0, name = 'UNDEAD', const = 'ABILITY_UNDEAD' },
  UNLIMITED_RETALIATION = { id = 0, name = 'UNLIMITED_RETALIATION', const = 'ABILITY_UNLIMITED_RETALIATION' },
  VENOM = { id = 0, name = 'VENOM', const = 'ABILITY_VENOM' },
  VORPAL_SWORD = { id = 0, name = 'VORPAL_SWORD', const = 'ABILITY_VORPAL_SWORD' },
  WARDING_ARROWS = { id = 0, name = 'WARDING_ARROWS', const = 'ABILITY_WARDING_ARROWS' },
  WAR_DANCE = { id = 0, name = 'WAR_DANCE', const = 'ABILITY_WAR_DANCE' },
  WEAKENING_AURA = { id = 0, name = 'WEAKENING_AURA', const = 'ABILITY_WEAKENING_AURA' },
  WEAKENING_STRIKE = { id = 0, name = 'WEAKENING_STRIKE', const = 'ABILITY_WEAKENING_STRIKE' },
  WHIP_STRIKE = { id = 0, name = 'WHIP_STRIKE', const = 'ABILITY_WHIP_STRIKE' },
  WHIRLWIND = { id = 0, name = 'WHIRLWIND', const = 'ABILITY_WHIRLWIND' },
  WOUND = { id = 0, name = 'WOUND', const = 'ABILITY_WOUND' },
})

CREATURE = __h55__local_56424_freeze({})
CREATURE.ACADEMY = __h55__local_56424_freeze({})
CREATURE.ACADEMY.ARCH_MAGI = __h55__local_56424_freeze({ name = 'CREATURE_ARCH_MAGI', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'ENERGY_CHANNEL', 'MAGIC_ATTACK', 'NO_RANGE_PENALTY' }) })
CREATURE.ACADEMY.COMBATMAGE = __h55__local_56424_freeze({ name = 'CREATURE_COMBATMAGE', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'ELDRITCH_AURA', 'MAGIC_ATTACK', 'NO_RANGE_PENALTY' }) })
CREATURE.ACADEMY.DJINNVIZIER = __h55__local_56424_freeze({ name = 'CREATURE_DJINNVIZIER', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_AIR', 'LUCK_GAMBLER', 'MAGIC_PROOF_25' }) })
CREATURE.ACADEMY.GENIE = __h55__local_56424_freeze({ name = 'CREATURE_GENIE', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'MAGIC_PROOF_50', 'RANDOM_CASTER' }) })
CREATURE.ACADEMY.GIANT = __h55__local_56424_freeze({ name = 'CREATURE_GIANT', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_MIND_CONTROL' }) })
CREATURE.ACADEMY.GREMLIN = __h55__local_56424_freeze({ name = 'CREATURE_GREMLIN', id = 0, BASE_GROWTH = 20, ABILITIES = __h55__local_56424_freeze({  }) })
CREATURE.ACADEMY.GREMLINSABOTEUR = __h55__local_56424_freeze({ name = 'CREATURE_GREMLINSABOTEUR', id = 0, BASE_GROWTH = 20, ABILITIES = __h55__local_56424_freeze({ 'SABOTAGE' }) })
CREATURE.ACADEMY.IRON_GOLEM = __h55__local_56424_freeze({ name = 'CREATURE_IRON_GOLEM', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_SLOW', 'MAGIC_PROOF_50', 'MECHANICAL' }) })
CREATURE.ACADEMY.MAGI = __h55__local_56424_freeze({ name = 'CREATURE_MAGI', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'MAGIC_ATTACK', 'NO_RANGE_PENALTY' }) })
CREATURE.ACADEMY.MARBLEGARGOYLE = __h55__local_56424_freeze({ name = 'CREATURE_MARBLEGARGOYLE', id = 0, BASE_GROWTH = 14, ABILITIES = __h55__local_56424_freeze({ 'AURA_OF_FIRE_VULNERABILITY', 'AURA_OF_ICE_VULNERABILITY', 'AURA_OF_LIGHTNING_VULNERABILITY', 'ELEMENTAL', 'ENRAGED', 'IMMUNITY_TO_EARTH' }) })
CREATURE.ACADEMY.MASTER_GENIE = __h55__local_56424_freeze({ name = 'CREATURE_MASTER_GENIE', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_CURSE', 'MAGIC_PROOF_50', 'RANDOM_CASTER_BLESS' }) })
CREATURE.ACADEMY.MASTER_GREMLIN = __h55__local_56424_freeze({ name = 'CREATURE_MASTER_GREMLIN', id = 0, BASE_GROWTH = 20, ABILITIES = __h55__local_56424_freeze({ 'REPAIR' }) })
CREATURE.ACADEMY.OBSIDIANGOLEM = __h55__local_56424_freeze({ name = 'CREATURE_OBSIDIANGOLEM', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'DESTRUCTION_MAGIC_MAGNETISM', 'ENCHANTED_OBSIDIAN', 'MECHANICAL' }) })
CREATURE.ACADEMY.OBSIDIAN_GARGOYLE = __h55__local_56424_freeze({ name = 'CREATURE_OBSIDIAN_GARGOYLE', id = 0, BASE_GROWTH = 14, ABILITIES = __h55__local_56424_freeze({ 'ELEMENTAL', 'ENRAGED', 'IMMUNITY_TO_EARTH' }) })
CREATURE.ACADEMY.RAKSHASA = __h55__local_56424_freeze({ name = 'CREATURE_RAKSHASA', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'NO_ENEMY_RETALIATION' }) })
CREATURE.ACADEMY.RAKSHASAKSHATRI = __h55__local_56424_freeze({ name = 'CREATURE_RAKSHASAKSHATRI', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'WHIRLWIND' }) })
CREATURE.ACADEMY.RAKSHASA_RUKH = __h55__local_56424_freeze({ name = 'CREATURE_RAKSHASA_RUKH', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'DASH', 'NO_ENEMY_RETALIATION' }) })
CREATURE.ACADEMY.STEEL_GOLEM = __h55__local_56424_freeze({ name = 'CREATURE_STEEL_GOLEM', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_SLOW', 'MAGIC_PROOF_75', 'MECHANICAL', 'UNLIMITED_RETALIATION' }) })
CREATURE.ACADEMY.STONE_GARGOYLE = __h55__local_56424_freeze({ name = 'CREATURE_STONE_GARGOYLE', id = 0, BASE_GROWTH = 14, ABILITIES = __h55__local_56424_freeze({ 'ELEMENTAL', 'ENRAGED', 'IMMUNITY_TO_EARTH' }) })
CREATURE.ACADEMY.STORMLORD = __h55__local_56424_freeze({ name = 'CREATURE_STORMLORD', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'CALL_STORM', 'IMMUNITY_TO_MIND_CONTROL', 'NO_MELEE_PENALTY' }) })
CREATURE.ACADEMY.TITAN = __h55__local_56424_freeze({ name = 'CREATURE_TITAN', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'CALL_LIGHTNING', 'IMMUNITY_TO_MIND_CONTROL' }) })

CREATURE.DUNGEON = __h55__local_56424_freeze({})
CREATURE.DUNGEON.ACIDBLOOD = __h55__local_56424_freeze({ name = 'CREATURE_ACIDBLOOD', id = 0, BASE_GROWTH = 0, ABILITIES = __h55__local_56424_freeze({  }) })
CREATURE.DUNGEON.ACIDICHYDRA = __h55__local_56424_freeze({ name = 'CREATURE_ACIDICHYDRA', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'ACID_BLOOD', 'ENRAGED', 'NO_ENEMY_RETALIATION', 'SIX_HEADED_ATTACK' }) })
CREATURE.DUNGEON.ASSASSIN = __h55__local_56424_freeze({ name = 'CREATURE_ASSASSIN', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'NO_MELEE_PENALTY', 'POISONOUS_ATTACK', 'RANGE_PENALTY' }) })
CREATURE.DUNGEON.BLACKRIDER = __h55__local_56424_freeze({ name = 'CREATURE_BLACKRIDER', id = 0, BASE_GROWTH = 4, ABILITIES = __h55__local_56424_freeze({ 'LIZARD_BITE', 'RIDE_BY_ATTACK' }) })
CREATURE.DUNGEON.BLACK_DRAGON = __h55__local_56424_freeze({ name = 'CREATURE_BLACK_DRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'FIRE_BREATH', 'IMMUNITY_TO_MAGIC' }) })
CREATURE.DUNGEON.BLOODWITCH2 = __h55__local_56424_freeze({ name = 'CREATURE_BLOODWITCH2', id = 0, BASE_GROWTH = 7, ABILITIES = __h55__local_56424_freeze({ 'MAGIC_PROOF_50', 'NO_ENEMY_RETALIATION', 'STRIKE_AND_RETURN' }) })
CREATURE.DUNGEON.BLOOD_WITCH = __h55__local_56424_freeze({ name = 'CREATURE_BLOOD_WITCH', id = 0, BASE_GROWTH = 7, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_CURSE', 'NO_ENEMY_RETALIATION', 'STRIKE_AND_RETURN' }) })
CREATURE.DUNGEON.CHAOS_HYDRA = __h55__local_56424_freeze({ name = 'CREATURE_CHAOS_HYDRA', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED', 'IMMUNITY_TO_SLOW', 'REGENERATION', 'SIX_HEADED_ATTACK', 'UNLIMITED_RETALIATION' }) })
CREATURE.DUNGEON.DEEP_DRAGON = __h55__local_56424_freeze({ name = 'CREATURE_DEEP_DRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'FIRE_BREATH', 'MAGIC_PROOF_50' }) })
CREATURE.DUNGEON.DEEP_DRAGON_PATTERN = __h55__local_56424_freeze({ name = 'CREATURE_DEEP_DRAGON_PATTERN', id = 0, BASE_GROWTH = 0, ABILITIES = __h55__local_56424_freeze({  }) })
CREATURE.DUNGEON.HALFCIRCLELARGEATTACK = __h55__local_56424_freeze({ name = 'CREATURE_HALFCIRCLELARGEATTACK', id = 0, BASE_GROWTH = 0, ABILITIES = __h55__local_56424_freeze({  }) })
CREATURE.DUNGEON.HYDRA = __h55__local_56424_freeze({ name = 'CREATURE_HYDRA', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED', 'REGENERATION', 'WHIRLWIND' }) })
CREATURE.DUNGEON.MATRIARCH = __h55__local_56424_freeze({ name = 'CREATURE_MATRIARCH', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'FAST_ATTACK', 'NO_MELEE_PENALTY' }) })
CREATURE.DUNGEON.MATRON = __h55__local_56424_freeze({ name = 'CREATURE_MATRON', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'NO_MELEE_PENALTY' }) })
CREATURE.DUNGEON.MINOTAUR = __h55__local_56424_freeze({ name = 'CREATURE_MINOTAUR', id = 0, BASE_GROWTH = 6, ABILITIES = __h55__local_56424_freeze({ 'BRAVERY' }) })
CREATURE.DUNGEON.MINOTAURCAPTAIN = __h55__local_56424_freeze({ name = 'CREATURE_MINOTAURCAPTAIN', id = 0, BASE_GROWTH = 6, ABILITIES = __h55__local_56424_freeze({ 'ARMORED', 'AURA_OF_BRAVERY' }) })
CREATURE.DUNGEON.MINOTAUR_KING = __h55__local_56424_freeze({ name = 'CREATURE_MINOTAUR_KING', id = 0, BASE_GROWTH = 6, ABILITIES = __h55__local_56424_freeze({ 'BRAVERY', 'BRUTALITY' }) })
CREATURE.DUNGEON.RAVAGER = __h55__local_56424_freeze({ name = 'CREATURE_RAVAGER', id = 0, BASE_GROWTH = 4, ABILITIES = __h55__local_56424_freeze({ 'LIZARD_BITE', 'RIDER_CHARGE' }) })
CREATURE.DUNGEON.REDDRAGON = __h55__local_56424_freeze({ name = 'CREATURE_REDDRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'FIRE_BREATH', 'IMMUNITY_TO_MIND_CONTROL', 'INCINERATE' }) })
CREATURE.DUNGEON.RIDER = __h55__local_56424_freeze({ name = 'CREATURE_RIDER', id = 0, BASE_GROWTH = 4, ABILITIES = __h55__local_56424_freeze({ 'RIDER_CHARGE' }) })
CREATURE.DUNGEON.SCOUT = __h55__local_56424_freeze({ name = 'CREATURE_SCOUT', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'NO_MELEE_PENALTY', 'RANGE_PENALTY' }) })
CREATURE.DUNGEON.SHADOWMISTRESS = __h55__local_56424_freeze({ name = 'CREATURE_SHADOWMISTRESS', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'LIFE_DRAIN', 'NO_ENEMY_RETALIATION', 'WHIP_STRIKE' }) })
CREATURE.DUNGEON.SIXHEADEDATTACK = __h55__local_56424_freeze({ name = 'CREATURE_SIXHEADEDATTACK', id = 0, BASE_GROWTH = 0, ABILITIES = __h55__local_56424_freeze({  }) })
CREATURE.DUNGEON.STALKER = __h55__local_56424_freeze({ name = 'CREATURE_STALKER', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'INVISIBILITY', 'POISONOUS_ATTACK' }) })
CREATURE.DUNGEON.WITCH = __h55__local_56424_freeze({ name = 'CREATURE_WITCH', id = 0, BASE_GROWTH = 7, ABILITIES = __h55__local_56424_freeze({ 'NO_ENEMY_RETALIATION', 'STRIKE_AND_RETURN' }) })

CREATURE.DWARF = __h55__local_56424_freeze({})
CREATURE.DWARF.AXE_FIGHTER = __h55__local_56424_freeze({ name = 'CREATURE_AXE_FIGHTER', id = 0, BASE_GROWTH = 14, ABILITIES = __h55__local_56424_freeze({ 'WOUND' }) })
CREATURE.DWARF.AXE_THROWER = __h55__local_56424_freeze({ name = 'CREATURE_AXE_THROWER', id = 0, BASE_GROWTH = 14, ABILITIES = __h55__local_56424_freeze({ 'NO_MELEE_PENALTY', 'WOUND' }) })
CREATURE.DWARF.BATTLERAGER = __h55__local_56424_freeze({ name = 'CREATURE_BATTLERAGER', id = 0, BASE_GROWTH = 6, ABILITIES = __h55__local_56424_freeze({ 'ANTI_GIANT', 'BASH', 'BATTLE_RAGE', 'IMMUNITY_TO_MIND_CONTROL' }) })
CREATURE.DWARF.BEAR_RAIDER = __h55__local_56424_freeze({ name = 'CREATURE_BEAR_RAIDER', id = 0, BASE_GROWTH = 7, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED' }) })
CREATURE.DWARF.BERSERKER = __h55__local_56424_freeze({ name = 'CREATURE_BERSERKER', id = 0, BASE_GROWTH = 6, ABILITIES = __h55__local_56424_freeze({ 'BERSERKER_RAGE', 'IMMUNITY_TO_MIND_CONTROL' }) })
CREATURE.DWARF.BLACKBEAR_RAIDER = __h55__local_56424_freeze({ name = 'CREATURE_BLACKBEAR_RAIDER', id = 0, BASE_GROWTH = 7, ABILITIES = __h55__local_56424_freeze({ 'ARMORED', 'ENRAGED', 'PAW_STRIKE' }) })
CREATURE.DWARF.BRAWLER = __h55__local_56424_freeze({ name = 'CREATURE_BRAWLER', id = 0, BASE_GROWTH = 6, ABILITIES = __h55__local_56424_freeze({ 'BASH', 'IMMUNITY_TO_MIND_CONTROL' }) })
CREATURE.DWARF.DEFENDER = __h55__local_56424_freeze({ name = 'CREATURE_DEFENDER', id = 0, BASE_GROWTH = 18, ABILITIES = __h55__local_56424_freeze({ 'ARMORED', 'ENRAGED', 'LARGE_SHIELD' }) })
CREATURE.DWARF.FIRE_DRAGON = __h55__local_56424_freeze({ name = 'CREATURE_FIRE_DRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'ELEMENTAL', 'FIRE_BREATH', 'FIRE_SHIELD', 'IMMUNITY_TO_FIRE' }) })
CREATURE.DWARF.FLAMEKEEPER = __h55__local_56424_freeze({ name = 'CREATURE_FLAMEKEEPER', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'MARK_OF_FIRE' }) })
CREATURE.DWARF.FLAME_MAGE = __h55__local_56424_freeze({ name = 'CREATURE_FLAME_MAGE', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'CROSS_ATTACK', 'MARK_OF_FIRE' }) })
CREATURE.DWARF.HARPOONER = __h55__local_56424_freeze({ name = 'CREATURE_HARPOONER', id = 0, BASE_GROWTH = 14, ABILITIES = __h55__local_56424_freeze({ 'HARPOON_STRIKE', 'MAGIC_PROOF_25' }) })
CREATURE.DWARF.LAVADRAGON = __h55__local_56424_freeze({ name = 'CREATURE_LAVADRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'ELEMENTAL', 'IMMUNITY_TO_FIRE', 'LIQUID_FLAME_BREATH' }) })
CREATURE.DWARF.MAGMA_DRAGON = __h55__local_56424_freeze({ name = 'CREATURE_MAGMA_DRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'ELEMENTAL', 'FIRE_BREATH', 'IMMUNITY_TO_FIRE', 'MAGMA_SHIELD' }) })
CREATURE.DWARF.RUNE_MAGE = __h55__local_56424_freeze({ name = 'CREATURE_RUNE_MAGE', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'MARK_OF_FIRE' }) })
CREATURE.DWARF.STONEDEFENDER = __h55__local_56424_freeze({ name = 'CREATURE_STONEDEFENDER', id = 0, BASE_GROWTH = 18, ABILITIES = __h55__local_56424_freeze({ 'ARMORED', 'ENRAGED', 'HOLD_GROUND', 'LARGE_SHIELD', 'PREPARED_POSITION' }) })
CREATURE.DWARF.STOUT_DEFENDER = __h55__local_56424_freeze({ name = 'CREATURE_STOUT_DEFENDER', id = 0, BASE_GROWTH = 18, ABILITIES = __h55__local_56424_freeze({ 'ARMORED', 'ENRAGED', 'LARGE_SHIELD', 'SHIELD_WALL' }) })
CREATURE.DWARF.THANE = __h55__local_56424_freeze({ name = 'CREATURE_THANE', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'STORMSTRIKE' }) })
CREATURE.DWARF.THUNDERTHANE = __h55__local_56424_freeze({ name = 'CREATURE_THUNDERTHANE', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_AIR', 'STORMBOLT', 'STORMSTRIKE' }) })
CREATURE.DWARF.WARLORD = __h55__local_56424_freeze({ name = 'CREATURE_WARLORD', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'FIRE_PROOF_50', 'FLAMESTRIKE', 'FLAMEWAVE' }) })
CREATURE.DWARF.WHITEBEARRIDER = __h55__local_56424_freeze({ name = 'CREATURE_WHITEBEARRIDER', id = 0, BASE_GROWTH = 7, ABILITIES = __h55__local_56424_freeze({ 'BEAR_ROAR', 'ENRAGED' }) })

CREATURE.FORTRESS = __h55__local_56424_freeze({})
CREATURE.FORTRESS.CROSSATTACK = __h55__local_56424_freeze({ name = 'CREATURE_CROSSATTACK', id = 0, BASE_GROWTH = 0, ABILITIES = __h55__local_56424_freeze({  }) })

CREATURE.HAVEN = __h55__local_56424_freeze({})
CREATURE.HAVEN.ANGEL = __h55__local_56424_freeze({ name = 'CREATURE_ANGEL', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_AIR' }) })
CREATURE.HAVEN.ARCHANGEL = __h55__local_56424_freeze({ name = 'CREATURE_ARCHANGEL', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_AIR', 'RESURRECT_ALLIES' }) })
CREATURE.HAVEN.ARCHER = __h55__local_56424_freeze({ name = 'CREATURE_ARCHER', id = 0, BASE_GROWTH = 12, ABILITIES = __h55__local_56424_freeze({ 'SCATTER_SHOT' }) })
CREATURE.HAVEN.BATTLEGRIFFIN = __h55__local_56424_freeze({ name = 'CREATURE_BATTLEGRIFFIN', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'BATTLE_FRENZY', 'IMMUNITY_TO_BLIND', 'PACK_DIVE', 'UNLIMITED_RETALIATION' }) })
CREATURE.HAVEN.CAVALIER = __h55__local_56424_freeze({ name = 'CREATURE_CAVALIER', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'JOUSTING' }) })
CREATURE.HAVEN.CHAMPION = __h55__local_56424_freeze({ name = 'CREATURE_CHAMPION', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'ACID_BREATH', 'JOUSTING' }) })
CREATURE.HAVEN.CLERIC = __h55__local_56424_freeze({ name = 'CREATURE_CLERIC', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'NO_MELEE_PENALTY', 'PURGER', 'RANGE_PENALTY' }) })
CREATURE.HAVEN.FOOTMAN = __h55__local_56424_freeze({ name = 'CREATURE_FOOTMAN', id = 0, BASE_GROWTH = 10, ABILITIES = __h55__local_56424_freeze({ 'BASH', 'ENRAGED', 'LARGE_SHIELD' }) })
CREATURE.HAVEN.GRIFFIN = __h55__local_56424_freeze({ name = 'CREATURE_GRIFFIN', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'UNLIMITED_RETALIATION' }) })
CREATURE.HAVEN.LANDLORD = __h55__local_56424_freeze({ name = 'CREATURE_LANDLORD', id = 0, BASE_GROWTH = 22, ABILITIES = __h55__local_56424_freeze({ 'BRUTALITY', 'TAXPAYER' }) })
CREATURE.HAVEN.LONGBOWMAN = __h55__local_56424_freeze({ name = 'CREATURE_LONGBOWMAN', id = 0, BASE_GROWTH = 12, ABILITIES = __h55__local_56424_freeze({ 'PRECISE_SHOT' }) })
CREATURE.HAVEN.MARKSMAN = __h55__local_56424_freeze({ name = 'CREATURE_MARKSMAN', id = 0, BASE_GROWTH = 12, ABILITIES = __h55__local_56424_freeze({ 'SCATTER_SHOT' }) })
CREATURE.HAVEN.MILITIAMAN = __h55__local_56424_freeze({ name = 'CREATURE_MILITIAMAN', id = 0, BASE_GROWTH = 22, ABILITIES = __h55__local_56424_freeze({ 'BASH', 'TAXPAYER' }) })
CREATURE.HAVEN.PALADIN = __h55__local_56424_freeze({ name = 'CREATURE_PALADIN', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_BERSERK', 'JOUSTING', 'LAY_HANDS' }) })
CREATURE.HAVEN.PEASANT = __h55__local_56424_freeze({ name = 'CREATURE_PEASANT', id = 0, BASE_GROWTH = 22, ABILITIES = __h55__local_56424_freeze({ 'TAXPAYER' }) })
CREATURE.HAVEN.PRIEST = __h55__local_56424_freeze({ name = 'CREATURE_PRIEST', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'NO_MELEE_PENALTY', 'RANGE_PENALTY' }) })
CREATURE.HAVEN.ROYAL_GRIFFIN = __h55__local_56424_freeze({ name = 'CREATURE_ROYAL_GRIFFIN', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'BATTLE_DIVE', 'IMMUNITY_TO_BLIND', 'UNLIMITED_RETALIATION' }) })
CREATURE.HAVEN.SERAPH = __h55__local_56424_freeze({ name = 'CREATURE_SERAPH', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'FIRE_PROOF_50' }) })
CREATURE.HAVEN.SWORDSMAN = __h55__local_56424_freeze({ name = 'CREATURE_SWORDSMAN', id = 0, BASE_GROWTH = 10, ABILITIES = __h55__local_56424_freeze({ 'BASH', 'ENRAGED', 'LARGE_SHIELD', 'SHIELD_OTHER' }) })
CREATURE.HAVEN.VINDICATOR = __h55__local_56424_freeze({ name = 'CREATURE_VINDICATOR', id = 0, BASE_GROWTH = 10, ABILITIES = __h55__local_56424_freeze({ 'CLEAVE', 'ENRAGED', 'LARGE_SHIELD' }) })
CREATURE.HAVEN.ZEALOT = __h55__local_56424_freeze({ name = 'CREATURE_ZEALOT', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'MARK_OF_FIRE', 'NO_MELEE_PENALTY', 'RANGE_PENALTY' }) })

CREATURE.INFERNO = __h55__local_56424_freeze({})
CREATURE.INFERNO.ARCHDEMON = __h55__local_56424_freeze({ name = 'CREATURE_ARCHDEMON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'IMMUNITY_TO_EARTH', 'SUMMON_OTHER' }) })
CREATURE.INFERNO.ARCHDEVIL = __h55__local_56424_freeze({ name = 'CREATURE_ARCHDEVIL', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'BALOR_SUMMONIG', 'DEMONIC', 'FIRE_PROOF_50' }) })
CREATURE.INFERNO.BALOR = __h55__local_56424_freeze({ name = 'CREATURE_BALOR', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'VORPAL_SWORD' }) })
CREATURE.INFERNO.CERBERIUS = __h55__local_56424_freeze({ name = 'CREATURE_CERBERIUS', id = 0, BASE_GROWTH = 8, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'NO_ENEMY_RETALIATION', 'SPRAY_ATTACK' }) })
CREATURE.INFERNO.DEMON = __h55__local_56424_freeze({ name = 'CREATURE_DEMON', id = 0, BASE_GROWTH = 15, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'ENRAGED' }) })
CREATURE.INFERNO.DEVIL = __h55__local_56424_freeze({ name = 'CREATURE_DEVIL', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'IMMUNITY_TO_EARTH' }) })
CREATURE.INFERNO.FAMILIAR = __h55__local_56424_freeze({ name = 'CREATURE_FAMILIAR', id = 0, BASE_GROWTH = 17, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'MANA_DESTROYER' }) })
CREATURE.INFERNO.FIREBREATHERHOUND = __h55__local_56424_freeze({ name = 'CREATURE_FIREBREATHERHOUND', id = 0, BASE_GROWTH = 8, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'NO_ENEMY_RETALIATION', 'THREE_HEADED_ATTACK' }) })
CREATURE.INFERNO.FRIGHTFULNIGHTMARE = __h55__local_56424_freeze({ name = 'CREATURE_FRIGHTFULNIGHTMARE', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'CURSING_ATTACK', 'DEMONIC', 'FIRE_PROOF_50', 'SEARING_AURA' }) })
CREATURE.INFERNO.HELLHOUND = __h55__local_56424_freeze({ name = 'CREATURE_HELLHOUND', id = 0, BASE_GROWTH = 8, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC' }) })
CREATURE.INFERNO.HELLMARE = __h55__local_56424_freeze({ name = 'CREATURE_HELLMARE', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'FEAR', 'FRIGHT_AURA', 'MAGIC_PROOF_25' }) })
CREATURE.INFERNO.HORNEDDEMON = __h55__local_56424_freeze({ name = 'CREATURE_HORNEDDEMON', id = 0, BASE_GROWTH = 15, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'ENRAGED', 'EXPLOSION' }) })
CREATURE.INFERNO.HORNEDLEAPER = __h55__local_56424_freeze({ name = 'CREATURE_HORNEDLEAPER', id = 0, BASE_GROWTH = 15, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'ENRAGED', 'LEAP' }) })
CREATURE.INFERNO.IMP = __h55__local_56424_freeze({ name = 'CREATURE_IMP', id = 0, BASE_GROWTH = 17, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'SYPHON_MANA' }) })
CREATURE.INFERNO.INFERNALSUCCUBUS = __h55__local_56424_freeze({ name = 'CREATURE_INFERNALSUCCUBUS', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'CHAIN_SHOT', 'DEMONIC', 'IMMUNITY_TO_BERSERK', 'RANGED_RETALIATE' }) })
CREATURE.INFERNO.NIGHTMARE = __h55__local_56424_freeze({ name = 'CREATURE_NIGHTMARE', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'FEAR', 'MAGIC_PROOF_25' }) })
CREATURE.INFERNO.PITFIEND = __h55__local_56424_freeze({ name = 'CREATURE_PITFIEND', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC' }) })
CREATURE.INFERNO.PITSPAWN = __h55__local_56424_freeze({ name = 'CREATURE_PITSPAWN', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'AXE_OF_SLAUGHTER', 'DEMONIC' }) })
CREATURE.INFERNO.QUASIT = __h55__local_56424_freeze({ name = 'CREATURE_QUASIT', id = 0, BASE_GROWTH = 17, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'MANA_STEALER' }) })
CREATURE.INFERNO.SUCCUBUS = __h55__local_56424_freeze({ name = 'CREATURE_SUCCUBUS', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'RANGED_RETALIATE' }) })
CREATURE.INFERNO.SUCCUBUSSEDUCER = __h55__local_56424_freeze({ name = 'CREATURE_SUCCUBUSSEDUCER', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'DEMONIC', 'IMMUNITY_TO_HYPNOTIZE', 'MARK_OF_FIRE', 'RANGED_RETALIATE', 'SEDUCE' }) })

CREATURE.NECROPOLIS = __h55__local_56424_freeze({})
CREATURE.NECROPOLIS.BANSHEE = __h55__local_56424_freeze({ name = 'CREATURE_BANSHEE', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'DEATH_WAIL', 'UNDEAD' }) })
CREATURE.NECROPOLIS.BONE_DRAGON = __h55__local_56424_freeze({ name = 'CREATURE_BONE_DRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'UNDEAD' }) })
CREATURE.NECROPOLIS.DEMILICH = __h55__local_56424_freeze({ name = 'CREATURE_DEMILICH', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'DEATH_CLOUD', 'UNDEAD' }) })
CREATURE.NECROPOLIS.DISEASEZOMBIE = __h55__local_56424_freeze({ name = 'CREATURE_DISEASEZOMBIE', id = 0, BASE_GROWTH = 16, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED', 'UNDEAD', 'WEAKENING_AURA' }) })
CREATURE.NECROPOLIS.GHOSTS = __h55__local_56424_freeze({ name = 'CREATURE_GHOSTS', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'INCORPOREAL', 'MANA_DRAIN', 'UNDEAD' }) })
CREATURE.NECROPOLIS.HORRORDRAGON = __h55__local_56424_freeze({ name = 'CREATURE_HORRORDRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'SORROW_STRIKE', 'UNDEAD' }) })
CREATURE.NECROPOLIS.LICH = __h55__local_56424_freeze({ name = 'CREATURE_LICH', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'DEATH_CLOUD', 'UNDEAD' }) })
CREATURE.NECROPOLIS.LICHMASTER = __h55__local_56424_freeze({ name = 'CREATURE_LICHMASTER', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'UNDEAD' }) })
CREATURE.NECROPOLIS.MANES = __h55__local_56424_freeze({ name = 'CREATURE_MANES', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'INCORPOREAL', 'UNDEAD' }) })
CREATURE.NECROPOLIS.NOSFERATU = __h55__local_56424_freeze({ name = 'CREATURE_NOSFERATU', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'LIFE_DRAIN', 'SLEEPING_STRIKE', 'UNDEAD' }) })
CREATURE.NECROPOLIS.POLTERGEIST = __h55__local_56424_freeze({ name = 'CREATURE_POLTERGEIST', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'AMMO_STEAL', 'INCORPOREAL', 'UNDEAD' }) })
CREATURE.NECROPOLIS.SHADOW_DRAGON = __h55__local_56424_freeze({ name = 'CREATURE_SHADOW_DRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'CURSING_ATTACK', 'HORROR_OF_THE_DEATH', 'UNDEAD' }) })
CREATURE.NECROPOLIS.SKELETON = __h55__local_56424_freeze({ name = 'CREATURE_SKELETON', id = 0, BASE_GROWTH = 20, ABILITIES = __h55__local_56424_freeze({ 'LARGE_SHIELD', 'UNDEAD' }) })
CREATURE.NECROPOLIS.SKELETONWARRIOR = __h55__local_56424_freeze({ name = 'CREATURE_SKELETONWARRIOR', id = 0, BASE_GROWTH = 20, ABILITIES = __h55__local_56424_freeze({ 'BASH', 'LARGE_SHIELD', 'UNDEAD' }) })
CREATURE.NECROPOLIS.SKELETON_ARCHER = __h55__local_56424_freeze({ name = 'CREATURE_SKELETON_ARCHER', id = 0, BASE_GROWTH = 20, ABILITIES = __h55__local_56424_freeze({ 'UNDEAD' }) })
CREATURE.NECROPOLIS.VAMPIRE = __h55__local_56424_freeze({ name = 'CREATURE_VAMPIRE', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'LIFE_DRAIN', 'NO_ENEMY_RETALIATION', 'UNDEAD' }) })
CREATURE.NECROPOLIS.VAMPIRE_LORD = __h55__local_56424_freeze({ name = 'CREATURE_VAMPIRE_LORD', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'LIFE_DRAIN', 'NO_ENEMY_RETALIATION', 'UNDEAD' }) })
CREATURE.NECROPOLIS.WALKING_DEAD = __h55__local_56424_freeze({ name = 'CREATURE_WALKING_DEAD', id = 0, BASE_GROWTH = 16, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED', 'UNDEAD' }) })
CREATURE.NECROPOLIS.WIGHT = __h55__local_56424_freeze({ name = 'CREATURE_WIGHT', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'UNDEAD' }) })
CREATURE.NECROPOLIS.WRAITH = __h55__local_56424_freeze({ name = 'CREATURE_WRAITH', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'HARM_TOUCH', 'UNDEAD' }) })
CREATURE.NECROPOLIS.ZOMBIE = __h55__local_56424_freeze({ name = 'CREATURE_ZOMBIE', id = 0, BASE_GROWTH = 16, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED', 'UNDEAD', 'WEAKENING_STRIKE' }) })

CREATURE.NEUTRALS = __h55__local_56424_freeze({})
CREATURE.NEUTRALS.AIR_ELEMENTAL = __h55__local_56424_freeze({ name = 'CREATURE_AIR_ELEMENTAL', id = 0, BASE_GROWTH = 4, ABILITIES = __h55__local_56424_freeze({ 'CRYSTAL_SCALES', 'ELEMENTAL', 'IMMUNITY_TO_AIR', 'NO_ENEMY_RETALIATION' }) })
CREATURE.NEUTRALS.BLACK_KNIGHT = __h55__local_56424_freeze({ name = 'CREATURE_BLACK_KNIGHT', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'CURSING_ATTACK', 'UNDEAD' }) })
CREATURE.NEUTRALS.DEATH_KNIGHT = __h55__local_56424_freeze({ name = 'CREATURE_DEATH_KNIGHT', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'FRIGHT_AURA', 'UNDEAD', 'VORPAL_SWORD' }) })
CREATURE.NEUTRALS.EARTH_ELEMENTAL = __h55__local_56424_freeze({ name = 'CREATURE_EARTH_ELEMENTAL', id = 0, BASE_GROWTH = 4, ABILITIES = __h55__local_56424_freeze({ 'AURA_OF_MAGIC_RESISTANCE', 'CRYSTAL_SCALES', 'ELEMENTAL', 'IMMUNITY_TO_EARTH', 'UNLIMITED_RETALIATION' }) })
CREATURE.NEUTRALS.FIRE_ELEMENTAL = __h55__local_56424_freeze({ name = 'CREATURE_FIRE_ELEMENTAL', id = 0, BASE_GROWTH = 4, ABILITIES = __h55__local_56424_freeze({ 'CRYSTAL_SCALES', 'ELEMENTAL', 'FIRE_SHIELD', 'IMMUNITY_TO_FIRE' }) })
CREATURE.NEUTRALS.MANTICORE = __h55__local_56424_freeze({ name = 'CREATURE_MANTICORE', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'POISONOUS_ATTACK' }) })
CREATURE.NEUTRALS.MUMMY = __h55__local_56424_freeze({ name = 'CREATURE_MUMMY', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'HEXING_ATTACK', 'UNDEAD' }) })
CREATURE.NEUTRALS.PHOENIX = __h55__local_56424_freeze({ name = 'CREATURE_PHOENIX', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'ELEMENTAL', 'FIRE_SHIELD', 'IMMUNITY_TO_FIRE', 'REBIRTH' }) })
CREATURE.NEUTRALS.SNOWAPE = __h55__local_56424_freeze({ name = 'CREATURE_SNOWAPE', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'ELEMENTAL', 'MAGIC_PROOF_50', 'MANA_DRAIN' }) })
CREATURE.NEUTRALS.WATER_ELEMENTAL = __h55__local_56424_freeze({ name = 'CREATURE_WATER_ELEMENTAL', id = 0, BASE_GROWTH = 4, ABILITIES = __h55__local_56424_freeze({ 'CRYSTAL_SCALES', 'ELEMENTAL', 'IMMUNITY_TO_WATER' }) })
CREATURE.NEUTRALS.WOLF = __h55__local_56424_freeze({ name = 'CREATURE_WOLF', id = 0, BASE_GROWTH = 6, ABILITIES = __h55__local_56424_freeze({ 'HOWL', 'PACK_HUNTER' }) })

CREATURE.ORCS = __h55__local_56424_freeze({})
CREATURE.ORCS.BLOODEYEBEAM_PATTERNATTACK = __h55__local_56424_freeze({ name = 'CREATURE_BLOODEYEBEAM_PATTERNATTACK', id = 0, BASE_GROWTH = 0, ABILITIES = __h55__local_56424_freeze({  }) })
CREATURE.ORCS.CENTAUR1 = __h55__local_56424_freeze({ name = 'CREATURE_CENTAUR1', id = 0, BASE_GROWTH = 14, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'MANEURE' }) })
CREATURE.ORCS.CENTAUR2 = __h55__local_56424_freeze({ name = 'CREATURE_CENTAUR2', id = 0, BASE_GROWTH = 14, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'MANEURE' }) })
CREATURE.ORCS.CENTAURMARADEUR = __h55__local_56424_freeze({ name = 'CREATURE_CENTAURMARADEUR', id = 0, BASE_GROWTH = 14, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'MAGIC_PROOF_25', 'NO_MELEE_PENALTY' }) })
CREATURE.ORCS.CRUSHINGBLOW = __h55__local_56424_freeze({ name = 'CREATURE_CRUSHINGBLOW', id = 0, BASE_GROWTH = 0, ABILITIES = __h55__local_56424_freeze({  }) })
CREATURE.ORCS.CYCLOP1 = __h55__local_56424_freeze({ name = 'CREATURE_CYCLOP1', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'SWALLOW_GOBLIN' }) })
CREATURE.ORCS.CYCLOP2 = __h55__local_56424_freeze({ name = 'CREATURE_CYCLOP2', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'CRUSHING_BLOW', 'DEMON_RAGED', 'GOBLIN_THROWER', 'RANGE_PENALTY', 'SWALLOW_GOBLIN' }) })
CREATURE.ORCS.CYCLOPBLOODEYED = __h55__local_56424_freeze({ name = 'CREATURE_CYCLOPBLOODEYED', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'EVIL_EYE', 'GOBLIN_THROWER', 'RANGE_PENALTY', 'SWALLOW_GOBLIN' }) })
CREATURE.ORCS.GOBLIN1 = __h55__local_56424_freeze({ name = 'CREATURE_GOBLIN1', id = 0, BASE_GROWTH = 25, ABILITIES = __h55__local_56424_freeze({ 'COWARDICE', 'DEMON_RAGED', 'TREACHERY' }) })
CREATURE.ORCS.GOBLIN2 = __h55__local_56424_freeze({ name = 'CREATURE_GOBLIN2', id = 0, BASE_GROWTH = 25, ABILITIES = __h55__local_56424_freeze({ 'COWARDICE', 'DEMON_RAGED', 'SET_SNARES' }) })
CREATURE.ORCS.GOBLINDEFILER = __h55__local_56424_freeze({ name = 'CREATURE_GOBLINDEFILER', id = 0, BASE_GROWTH = 25, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'IMMUNITY_TO_MIND_CONTROL' }) })
CREATURE.ORCS.ORC1 = __h55__local_56424_freeze({ name = 'CREATURE_ORC1', id = 0, BASE_GROWTH = 11, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'ENRAGED' }) })
CREATURE.ORCS.ORC2 = __h55__local_56424_freeze({ name = 'CREATURE_ORC2', id = 0, BASE_GROWTH = 11, ABILITIES = __h55__local_56424_freeze({ 'BRUTALITY', 'DEMON_RAGED', 'ENRAGED' }) })
CREATURE.ORCS.ORCCHIEF1 = __h55__local_56424_freeze({ name = 'CREATURE_ORCCHIEF1', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'DOUBLE_ATTACK' }) })
CREATURE.ORCS.ORCCHIEF2 = __h55__local_56424_freeze({ name = 'CREATURE_ORCCHIEF2', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'BRAVERY', 'DEMON_RAGED', 'DOUBLE_ATTACK', 'FRIGHT_AURA' }) })
CREATURE.ORCS.ORCCHIEFCHIEFTAIN = __h55__local_56424_freeze({ name = 'CREATURE_ORCCHIEFCHIEFTAIN', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'ORDER_OF_THE_CHIEF', 'PRESENCE_OF_COMMANDER' }) })
CREATURE.ORCS.ORCWARMONGER = __h55__local_56424_freeze({ name = 'CREATURE_ORCWARMONGER', id = 0, BASE_GROWTH = 11, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'ENRAGED', 'FIERCE_RETALIATION', 'TAUNT' }) })
CREATURE.ORCS.SHAMAN1 = __h55__local_56424_freeze({ name = 'CREATURE_SHAMAN1', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED' }) })
CREATURE.ORCS.SHAMAN2 = __h55__local_56424_freeze({ name = 'CREATURE_SHAMAN2', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'PURGER', 'SACRIFICE_GOBLIN' }) })
CREATURE.ORCS.SHAMANHAG = __h55__local_56424_freeze({ name = 'CREATURE_SHAMANHAG', id = 0, BASE_GROWTH = 5, ABILITIES = __h55__local_56424_freeze({ 'DEMON_RAGED', 'FAST_ATTACK', 'HEXING_ATTACK', 'SACRIFICE_GOBLIN' }) })
CREATURE.ORCS.WYVERN1 = __h55__local_56424_freeze({ name = 'CREATURE_WYVERN1', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'REGENERATION' }) })
CREATURE.ORCS.WYVERN2 = __h55__local_56424_freeze({ name = 'CREATURE_WYVERN2', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_BERSERK', 'REGENERATION', 'VENOM' }) })
CREATURE.ORCS.WYVERNPAOKAI = __h55__local_56424_freeze({ name = 'CREATURE_WYVERNPAOKAI', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_BLIND', 'LIGHTNING_BREATH', 'SCAVENGER' }) })

CREATURE.PRESERVE = __h55__local_56424_freeze({})
CREATURE.PRESERVE.ACIDBREATH = __h55__local_56424_freeze({ name = 'CREATURE_ACIDBREATH', id = 0, BASE_GROWTH = 0, ABILITIES = __h55__local_56424_freeze({  }) })
CREATURE.PRESERVE.ANGERTREANT = __h55__local_56424_freeze({ name = 'CREATURE_ANGERTREANT', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED', 'ENTANGLING_ROOTS', 'IMMUNITY_TO_SLOW', 'RAGE_OF_THE_FOREST' }) })
CREATURE.PRESERVE.BLADESINGER = __h55__local_56424_freeze({ name = 'CREATURE_BLADESINGER', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'AGILITY', 'ENRAGED' }) })
CREATURE.PRESERVE.BLADE_JUGGLER = __h55__local_56424_freeze({ name = 'CREATURE_BLADE_JUGGLER', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED' }) })
CREATURE.PRESERVE.DRUID = __h55__local_56424_freeze({ name = 'CREATURE_DRUID', id = 0, BASE_GROWTH = 4, ABILITIES = __h55__local_56424_freeze({  }) })
CREATURE.PRESERVE.DRUID_ELDER = __h55__local_56424_freeze({ name = 'CREATURE_DRUID_ELDER', id = 0, BASE_GROWTH = 4, ABILITIES = __h55__local_56424_freeze({ 'MANA_FEED' }) })
CREATURE.PRESERVE.DRYAD = __h55__local_56424_freeze({ name = 'CREATURE_DRYAD', id = 0, BASE_GROWTH = 12, ABILITIES = __h55__local_56424_freeze({ 'NO_ENEMY_RETALIATION', 'SPRAY_ATTACK', 'SYPHON_MANA' }) })
CREATURE.PRESERVE.GOLD_DRAGON = __h55__local_56424_freeze({ name = 'CREATURE_GOLD_DRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'FIRE_BREATH', 'IMMUNITY_TO_EARTH' }) })
CREATURE.PRESERVE.GRAND_ELF = __h55__local_56424_freeze({ name = 'CREATURE_GRAND_ELF', id = 0, BASE_GROWTH = 7, ABILITIES = __h55__local_56424_freeze({ 'ELVES_DOUBLE_SHOT', 'WARDING_ARROWS' }) })
CREATURE.PRESERVE.GREEN_DRAGON = __h55__local_56424_freeze({ name = 'CREATURE_GREEN_DRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'FIRE_BREATH', 'IMMUNITY_TO_EARTH' }) })
CREATURE.PRESERVE.HIGHDRUID = __h55__local_56424_freeze({ name = 'CREATURE_HIGHDRUID', id = 0, BASE_GROWTH = 4, ABILITIES = __h55__local_56424_freeze({ 'POWER_FEED' }) })
CREATURE.PRESERVE.PIXIE = __h55__local_56424_freeze({ name = 'CREATURE_PIXIE', id = 0, BASE_GROWTH = 12, ABILITIES = __h55__local_56424_freeze({ 'NO_ENEMY_RETALIATION', 'SPRAY_ATTACK' }) })
CREATURE.PRESERVE.RAINBOWDRAGON = __h55__local_56424_freeze({ name = 'CREATURE_RAINBOWDRAGON', id = 0, BASE_GROWTH = 1, ABILITIES = __h55__local_56424_freeze({ 'IMMUNITY_TO_AIR', 'LIGHTNING_BREATH' }) })
CREATURE.PRESERVE.SHARPSHOOTER = __h55__local_56424_freeze({ name = 'CREATURE_SHARPSHOOTER', id = 0, BASE_GROWTH = 7, ABILITIES = __h55__local_56424_freeze({ 'NO_RANGE_PENALTY', 'PIERCING_ARROW' }) })
CREATURE.PRESERVE.SPRAYATTACK = __h55__local_56424_freeze({ name = 'CREATURE_SPRAYATTACK', id = 0, BASE_GROWTH = 0, ABILITIES = __h55__local_56424_freeze({  }) })
CREATURE.PRESERVE.SPRITE = __h55__local_56424_freeze({ name = 'CREATURE_SPRITE', id = 0, BASE_GROWTH = 12, ABILITIES = __h55__local_56424_freeze({ 'NO_ENEMY_RETALIATION', 'SPRAY_ATTACK', 'TREEANT_UNION' }) })
CREATURE.PRESERVE.TREANT = __h55__local_56424_freeze({ name = 'CREATURE_TREANT', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED', 'ENTANGLING_ROOTS' }) })
CREATURE.PRESERVE.TREANT_GUARDIAN = __h55__local_56424_freeze({ name = 'CREATURE_TREANT_GUARDIAN', id = 0, BASE_GROWTH = 2, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED', 'ENTANGLING_ROOTS', 'TAKE_ROOTS' }) })
CREATURE.PRESERVE.UNICORN = __h55__local_56424_freeze({ name = 'CREATURE_UNICORN', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'AURA_OF_MAGIC_RESISTANCE' }) })
CREATURE.PRESERVE.WAR_DANCER = __h55__local_56424_freeze({ name = 'CREATURE_WAR_DANCER', id = 0, BASE_GROWTH = 9, ABILITIES = __h55__local_56424_freeze({ 'ENRAGED', 'WAR_DANCE' }) })
CREATURE.PRESERVE.WAR_UNICORN = __h55__local_56424_freeze({ name = 'CREATURE_WAR_UNICORN', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'AURA_OF_MAGIC_RESISTANCE', 'BLINDING_ATTACK' }) })
CREATURE.PRESERVE.WHITEUNICORN = __h55__local_56424_freeze({ name = 'CREATURE_WHITEUNICORN', id = 0, BASE_GROWTH = 3, ABILITIES = __h55__local_56424_freeze({ 'BLINDING_ATTACK', 'BOND_OF_LIGHT', 'IMMUNITY_TO_BLIND' }) })
CREATURE.PRESERVE.WOOD_ELF = __h55__local_56424_freeze({ name = 'CREATURE_WOOD_ELF', id = 0, BASE_GROWTH = 7, ABILITIES = __h55__local_56424_freeze({ 'ELVES_DOUBLE_SHOT' }) })

CREATURE.UNKNOWN = __h55__local_56424_freeze({ name = 'CREATURE_UNKNOWN', id = 0, BASE_GROWTH = 0, ABILITIES = __h55__local_56424_freeze({}) })

-- Optional self-test: set H55_ENUMS_SELFTEST = 1 before doFile() to print samples.
if H55_ENUMS_SELFTEST then
  function __h55__local_56424__arr(t) local s='{' local i=1 while t[i]~=nil do if i>1 then s=s..', ' end s=s..tostring(t[i]) i=i+1 end return s..'}' end
  function __h55__local_56424__dump(obj) write('{ name='..obj.name..', id='..obj.id..', BASE_GROWTH='..obj.BASE_GROWTH..', ABILITIES='..__h55__local_56424__arr(obj.ABILITIES)..' }\n') end
  if CREATURE.HAVEN and CREATURE.HAVEN.ANGEL then write('CREATURE.HAVEN.ANGEL -> '); __h55__local_56424__dump(CREATURE.HAVEN.ANGEL) end
  if CREATURE.ACADEMY and CREATURE.ACADEMY.DJINN_VIZIER then write('CREATURE.ACADEMY.DJINN_VIZIER -> '); __h55__local_56424__dump(CREATURE.ACADEMY.DJINN_VIZIER) end
  if CREATURE.NECROPOLIS and CREATURE.NECROPOLIS.SKELETON then write('CREATURE.NECROPOLIS.SKELETON -> '); __h55__local_56424__dump(CREATURE.NECROPOLIS.SKELETON) end
end
